# Generated by Django 5.2 on 2025-04-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='selected_activities',
            field=models.TextField(blank=True),
        ),
    ]
