# Generated by Django 5.2 on 2025-04-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_shuffled_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='shuffled_activities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
