# Generated by Django 5.2 on 2025-04-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_trip_shuffled_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='shuffled_activities',
        ),
    ]
