# Generated by Django 5.2 on 2025-04-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_selected_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='shuffled_activities',
            field=models.TextField(blank=True),
        ),
    ]
