# Generated by Django 5.2 on 2025-05-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_alter_trip_selected_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='itinerary_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
